# Generated by Django 3.1 on 2020-08-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_no', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('said_by', models.CharField(max_length=50)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
