# Generated by Django 3.1 on 2020-08-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_emailstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailstore',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
