# Generated by Django 3.1 on 2020-08-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_card_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='insta_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
