# Generated by Django 3.1 on 2020-09-05 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_card_insta_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
